---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---

## Vanessa Zapata

  * vanessa.zapata@utexas.edu
  * [github.com/brownsugarpoptarts444](github.com/brownsugarpoptarts444)

## Skills
* Organization
* Empathy
* Knowing all lyrics to all One Direction songs

## Education 

#### University of Texas at Austin
  * B.S.A in Biology   |   2021
  * Minor in Sociology
  
  * Austin, Texas
  
  
## Interests

* Intersections of biology and sociology
* Harry Styles

## Experience



#### Work 

Churro Alley
  + store associate | 2017

#### Volunteer

* North and Central Texas Food Bank
  + packaging donated goods in warehouse to be distributed to food insecure populations
  
* Heritage Park & Rehab Center, Austin, TX
  + organizing and playing bingo with nursing home residents

## Accomplishments

* awarded EMT certification | 2017

* Member of Women in Medicine | 2018 - 2021


* Member of Latinx Health Professions Organization | 2019 - 2021
    + selected for preceptorship program 





